# Generated by Django 4.2.13 on 2024-07-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.TextField()),
                ('descriptions', models.TextField()),
                ('image', models.ImageField(upload_to='question_image/')),
                ('testcase', models.JSONField(null=True)),
            ],
        ),
    ]
