# Generated by Django 4.2.13 on 2024-07-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='testcase',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
